### ISSUE TITLE
error: undefined symbol: HMAC_CTX_init

### ISSUE THREAD

**Issue by garrylea** [medooze/media-server-demo-node#19]
when i deploy it, I get this error. 

================================================
$ node index.js 172.16.125.32
internal/modules/cjs/loader.js:717
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/lichao/node_modules/medooze-media-server/build/Release/medooze-media-server.node: undefined symbol: HMAC_CTX_init
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/lichao/node_modules/medooze-media-server/lib/Native.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

========================================================================

I have install the openssl1.0.2 by it's source and I can find it when i run "readelf -a /usr/local/openssl1.0.2/lib/libcrypto.a | grep HMAC_CTX_init". it's result is ：
=========================================================
    29: 00000000000008d0    40 FUNC    GLOBAL DEFAULT    1 HMAC_CTX_init
0000000002b3  002600000004 R_X86_64_PLT32    0000000000000000 HMAC_CTX_init - 4
00000000032f  002600000004 R_X86_64_PLT32    0000000000000000 HMAC_CTX_init - 4
000000000350  002600000004 R_X86_64_PLT32    0000000000000000 HMAC_CTX_init - 4
    38: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND HMAC_CTX_init
000000000065  000e00000004 R_X86_64_PLT32    0000000000000000 HMAC_CTX_init - 4
    14: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND HMAC_CTX_init
0000000000e9  001200000004 R_X86_64_PLT32    0000000000000000 HMAC_CTX_init - 4
    18: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND HMAC_CTX_init
==========================================================================

so, I don't know why it generate this error.

**Comment by garrylea** [comment]
I have resolved it.

**Comment by murillo128** [comment]
what happened?

**Comment by garrylea** [comment]
I find must firstly install media-server-node, then to install media-server-demo-node， it will sucessfully to deploy it .  so I think you should write it on your ReadMe file for helping others.
