### ISSUE TITLE
Compile media-server error

### ISSUE THREAD

**Issue by Justme0** [medooze/media-server-demo-node#36]
When I execute `npm i`, there are many warnings and **errors** in media-server. I am not sure it's node-gyp or high-version gcc problem?

1. Some of error
```
1st:

  COPY Release/libmp4v2.a
  AR(target) Release/obj.target/external/srtp/srtp.a
  COPY Release/srtp.a
  CXX(target) Release/obj.target/medooze-media-server/src/media-server_wrap.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_portable.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_sse42.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/crc32c/src/crc32c_arm64.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/ext/libdatachannels/src/Datachannels.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/src/ActiveSpeakerDetector.o
  CXX(target) Release/obj.target/medooze-media-server/media-server/src/EventLoop.o
../src/media-server_wrap.cxx: In function ‘void SWIG_V8_Raise(const char*)’:
../src/media-server_wrap.cxx:824:55: error: cannot convert ‘v8::MaybeLocal<v8::String>’ to ‘v8::Local<v8::String>’
  824 | #define SWIGV8_STRING_NEW(str) v8::String::NewFromUtf8(v8::Isolate::GetCurrent(), str)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       |
      |                                                       v8::MaybeLocal<v8::String>
../src/media-server_wrap.cxx:823:79: note: in definition of macro ‘SWIGV8_THROW_EXCEPTION’
  823 | #define SWIGV8_THROW_EXCEPTION(err) v8::Isolate::GetCurrent()->ThrowException(err)
      |                                                                               ^~~
../src/media-server_wrap.cxx:875:47: note: in expansion of macro ‘SWIGV8_STRING_NEW’
  875 |   SWIGV8_THROW_EXCEPTION(v8::Exception::Error(SWIGV8_STRING_NEW(msg)));
      |                                               ^~~~~~~~~~~~~~~~~
In file included from /home/justme0/.cache/node-gyp/14.15.4/include/node/node.h:67,
                 from ../src/media-server_wrap.cxx:171:
/home/justme0/.cache/node-gyp/14.15.4/include/node/v8.h:7196:43: note:   initializing argument 1 of ‘static v8::Local<v8::Value> v8::Exception::Error(v8::Local<v8::String>)’
 7196 |   static Local<Value> Error(Local<String> message);
      |                             ~~~~~~~~~~~~~~^~~~~~~


2nd:

../src/media-server_wrap.cxx: At global scope:
../src/media-server_wrap.cxx:2844:21: error: variable or field ‘medooze_initialize’ declared void
 2844 | #define SWIGV8_INIT medooze_initialize
      |                     ^~~~~~~~~~~~~~~~~~
../src/media-server_wrap.cxx:15200:6: note: in expansion of macro ‘SWIGV8_INIT’
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |      ^~~~~~~~~~~
../src/media-server_wrap.cxx:15200:23: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                       ^~~~~~
      |                       JobHandle
../src/media-server_wrap.cxx:15200:40: error: expected primary-expression before ‘>’ token
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                                        ^
../src/media-server_wrap.cxx:15200:42: error: ‘exports’ was not declared in this scope
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                                          ^~~~~~~
../src/media-server_wrap.cxx:15200:55: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                                                       ^~~~~~
      |                                                       JobHandle
../src/media-server_wrap.cxx:15200:72: error: expected primary-expression before ‘>’ token
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                                                                        ^
../src/media-server_wrap.cxx:15200:84: error: expected primary-expression before ‘)’ token
15200 | void SWIGV8_INIT (v8::Handle<v8::Object> exports, v8::Handle<v8::Object> /*module*/)
      |                                                                                    ^
In file included from ../src/media-server_wrap.cxx:171:
../src/media-server_wrap.cxx:16062:22: error: ‘medooze_initialize’ was not declared in this scope
16062 | NODE_MODULE(medooze, medooze_initialize)
      |                      ^~~~~~~~~~~~~~~~~~

...

make: Leaving directory `/home/justme0/media-server-demo-node/node_modules/medooze-media-server/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/justme0/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1062.9.1.el7.x86_64
gyp ERR! command "/home/justme0/node-v14.15.4-linux-x64/bin/node" "/home/justme0/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd /home/justme0/media-server-demo-node/node_modules/medooze-media-server
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-media-server@0.100.0 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the medooze-media-server@0.100.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justme0/.npm/_logs/2021-01-24T08_24_19_558Z-debug.log
```

Critical log in 2021-01-24T08_24_19_558Z-debug.log:
```
830 verbose stack Error: medooze-media-server@0.100.0 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
830 verbose stack Exit status 1
830 verbose stack     at EventEmitter.<anonymous> (/home/justme0/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
830 verbose stack     at EventEmitter.emit (events.js:315:20)
830 verbose stack     at ChildProcess.<anonymous> (/home/justme0/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
830 verbose stack     at ChildProcess.emit (events.js:315:20)
830 verbose stack     at maybeClose (internal/child_process.js:1048:16)
830 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
831 verbose pkgid medooze-media-server@0.100.0
832 verbose cwd /home/justme0/media-server-demo-node
833 verbose Linux 3.10.0-1062.9.1.el7.x86_64
834 verbose argv "/home/justme0/node-v14.15.4-linux-x64/bin/node" "/usr/local/bin/npm" "i"
835 verbose node v14.15.4
836 verbose npm  v6.14.10
837 error code ELIFECYCLE
838 error errno 1
839 error medooze-media-server@0.100.0 install: `test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
839 error Exit status 1
840 error Failed at the medooze-media-server@0.100.0 install script.
840 error This is probably not a problem with npm. There is likely additional logging output above.
841 verbose exit [ 1, true ]
```

I have read the media-server_wrap.cxx code generated by SWIG. Indeed there is a problem **cannot convert ‘v8::MaybeLocal<v8::String>’ to ‘v8::Local<v8::String>’**. `SWIGV8_STRING_NEW` return `MaybeLocal`, but the parameter of `Error` function is `Local`.

![cxx_err](https://user-images.githubusercontent.com/2346101/105625606-64284280-5e65-11eb-9881-54b65a2ad4a5.png)

I have not found conversion function between `MaybeLocal` and `Local` in  https://v8docs.nodesource.com/node-14.15/d8/d7d/classv8_1_1_maybe_local.html

2. My environment
node and npm are downloaded from official website
```
bash-4.2$ gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
bash-4.2$ node -v
v14.15.4
bash-4.2$ npm -v
6.14.10
bash-4.2$ npm install -g node-gyp
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/home/justme0/node-v14.15.4-linux-x64/bin/node-gyp -> /home/justme0/node-v14.15.4-linux-x64/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@7.1.2
added 97 packages from 66 contributors in 6.271s
```

node-gyp is lastest version 7.1.2 when installing, but 5.1.0 in log. Maybe that's key to problem?
```
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok ```
```

attachment

[media_error.zip](https://github.com/medooze/media-server-demo-node/files/5861879/media_error.zip)

### Solution
SWIG only supports to node v10. @notedit

**Comment by murillo128** [comment]
yes, only node 10 or lower supported yet.
