### ISSUE TITLE
medooze-media-server 0.23.0 throws an error

### ISSUE THREAD

**Issue by omartrigui** [medooze/media-server-demo-node#5]
```
ReferenceError: muted is not defined
at Transponder.mute (/home/talent/deploy/MeazrMediaStream/node_modules/medooze-media-server/lib/Transponder.js:68:26)
at Transponder.setIncomingTrack (/home/talent/deploy/MeazrMediaStream/node_modules/medooze-media-server/lib/Transponder.js:37:8)
at OutgoingStreamTrack.attachTo (/home/talent/deploy/MeazrMediaStream/node_modules/medooze-media-server/lib/OutgoingStreamTrack.js:172:20)
```

**Comment by murillo128** [comment]
Thanxs! Fixed on 0.23.1 and added tests so it doesn't happen again.
